spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/feastverse_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
upload:
  storage-type: local
  local:
    directory: upload
