spring:
  application:
    name: FeastVerse
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:db-init/data.sql
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-stacktrace: never

jwt:
  secret: ${JWT_SECRET}
  expiration: 1200000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: DEBUG
